# Generated by Django 5.1.4 on 2025-01-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FDS', '0002_remove_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='viewed_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='file_backup',
            old_name='performed_by',
            new_name='backuped_by',
        ),
    ]
