# Generated by Django 5.1.4 on 2025-01-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FDS', '0003_rename_viewed_date_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('standard_user', 'Standard_User'), ('viewer', 'Viewer')], max_length=50),
        ),
    ]
