# Generated by Django 5.1.4 on 2025-01-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FDS', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow_responsibility',
            name='workflow',
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
        migrations.DeleteModel(
            name='Workflow_Responsibility',
        ),
    ]
