# Generated by Django 5.1.4 on 2025-01-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FDS', '0005_remove_workflow_responsibility_workflow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('standard_user', 'Standard_User'), ('viewer', 'Viewer')], default='standard_user', max_length=50),
        ),
    ]
