# Generated by Django 5.1.4 on 2024-12-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audit_Logs',
            new_name='Audit_Log',
        ),
        migrations.RenameModel(
            old_name='Feedbacks',
            new_name='Feedback',
        ),
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
