# Generated by Django 5.1.4 on 2024-12-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_audit_logs_audit_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_uploaded_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
