# Generated by Django 5.1.4 on 2024-12-28 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_file_file_uploaded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Backup_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_file_name', models.CharField(max_length=255)),
                ('backup_file_path', models.FileField(upload_to='backups/')),
                ('backup_date', models.DateTimeField(auto_now_add=True)),
                ('backup_type', models.CharField(choices=[('FULL', 'Full Backup'), ('INCREMENTAL', 'Incremental Backup'), ('DIFFERENTIAL', 'Differential Backup')], max_length=20)),
                ('backup_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('IN_PROGRESS', 'In Progress')], default='IN_PROGRESS', max_length=20)),
                ('checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='base.file')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_performed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_date', models.DateTimeField(auto_now_add=True)),
                ('recovery_status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial Recovery')], max_length=20)),
                ('recovery_location', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True, null=True)),
                ('backup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recovery', to='base.backup_file')),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='base.file')),
                ('recovered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_performed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
