# Generated by Django 5.1.4 on 2024-12-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_filerecovery_recovery_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery_file',
            name='recovery_location',
            field=models.FileField(upload_to='recovery/'),
        ),
    ]
